In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os.path
from os import path
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras import backend as K
from sklearn.preprocessing import OneHotEncoder
from glob import iglob
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error
from keras.losses import MeanSquaredError
from scipy.stats import pearsonr
from keras import backend as K
from tensorflow.keras.losses import MeanSquaredLogarithmicError

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data1_train = pd.read_csv("/content/drive/MyDrive/Data mưa/cv1_data_train_92022.csv")
data1_test = pd.read_csv("/content/drive/MyDrive/Data mưa/cv1_data_test_92022.csv")
data2_train = pd.read_csv("/content/drive/MyDrive/Data mưa/cv2_data_train_92022.csv")
data2_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv2_data_test_92022.csv')
data3_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv3_data_train_92022.csv')
data3_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv3_data_test_92022.csv')
data4_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv4_data_train_92022.csv')
data4_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv4_data_test_92022.csv')
data5_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv5_data_train_92022.csv')
data5_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv5_data_test_92022.csv')
data6_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv6_data_train_92022.csv')
data6_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv6_data_test_92022.csv')
data7_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv7_data_train_92022.csv')
data7_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv7_data_test_92022.csv')
data8_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv8_data_train_92022.csv')
data8_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv8_data_test_92022.csv')
data9_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv9_data_train_92022.csv')
data9_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv9_data_test_92022.csv')
data10_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv10_data_train_92022.csv')
data10_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv10_data_test_92022.csv')
data11_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv11_data_train_92022.csv')
data11_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv11_data_test_92022.csv')
data12_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv12_data_train_92022.csv')
data12_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv12_data_test_92022.csv')
data13_train = pd.read_csv('/content/drive/MyDrive/Data mưa/cv13_data_train_92022.csv')
data13_test = pd.read_csv('/content/drive/MyDrive/Data mưa/cv13_data_test_92022.csv')

In [ ]:
def r(y_true, y_pred):
	mean_true = K.mean(y_true)
	mean_pred = K.mean(y_pred)
	return (K.sum((y_true - mean_true) * (y_pred - mean_pred)))/(K.sum(K.sqrt(K.pow(y_true - mean_true, 2) * K.pow(y_pred - mean_pred, 2))) + K.epsilon())

In [ ]:
data_train = data10_train
data_test = data10_test

In [ ]:
# data_train = pd.concat([data1_train, data1_test, data3_train, data3_test, data4_train, data4_test, data5_train, data5_test,
#                        data6_train, data6_test, data7_train, data7_test, data8_train, data8_test, data9_train, data9_test,
#                        data10_train, data10_test, data11_train, data11_test, data12_train, data12_test, data13_train, data13_test])
# data_test = pd.concat([data2_train, data2_test])

In [ ]:
data_train = data_train[data_train['value'] != 0]
data_test = data_test[data_test['value'] != 0]

In [ ]:
data_train = data_train.drop(columns = ['x_id', 'y_id', 'DEM_value', 'cloud_value'])

In [ ]:

data_test = data_test.drop(columns = ['x_id', 'y_id', 'DEM_value', 'cloud_value'])

In [ ]:
data_train['utc_time'] = pd.to_datetime(data_train['utc_time'])
data_train['hour'] = data_train['utc_time'].apply(lambda x: x.hour)
import datetime

def function(x):
    x = x.timetuple()
    jdate = x.tm_yday
    return(jdate)
data_train['date'] = data_train['utc_time'].apply(lambda x: function(x))

In [ ]:
data_test['utc_time'] = pd.to_datetime(data_test['utc_time'])
data_test['hour'] = data_test['utc_time'].apply(lambda x: x.hour)
import datetime

def function(x):
    x = x.timetuple()
    jdate = x.tm_yday
    return(jdate)
data_test['date'] = data_test['utc_time'].apply(lambda x: function(x))

In [ ]:


data_train['day'] = data_train['utc_time'].apply(lambda x: x.day)
data_train['month'] = data_train['utc_time'].apply(lambda x: x.month)

In [ ]:
data_test['day'] = data_test['utc_time'].apply(lambda x: x.day)
data_test['month'] = data_test['utc_time'].apply(lambda x: x.month)

In [ ]:
def fill_columns(data_test):
  data_test['day_1'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 1 else 0)
  data_test['day_2'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 2 else 0)
  data_test['day_3'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 3 else 0)
  data_test['day_4'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 4 else 0)
  data_test['day_5'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 5 else 0)
  data_test['day_6'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 6 else 0)
  data_test['day_7'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 7 else 0)
  data_test['day_8'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 8 else 0)
  data_test['day_9'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 9 else 0)
  data_test['day_10'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 10 else 0)
  data_test['day_11'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 11 else 0)
  data_test['day_12'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 12 else 0)
  data_test['day_13'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 13 else 0)
  data_test['day_14'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 14 else 0)
  data_test['day_15'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 15 else 0)
  data_test['day_16'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 16 else 0)
  data_test['day_17'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 17 else 0)
  data_test['day_18'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 18 else 0)
  data_test['day_19'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 19 else 0)
  data_test['day_20'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 20 else 0)
  data_test['day_21'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 21 else 0)
  data_test['day_22'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 22 else 0)
  data_test['day_23'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 23 else 0)
  data_test['day_24'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 24 else 0)
  data_test['day_25'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 25 else 0)
  data_test['day_26'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 26 else 0)
  data_test['day_27'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 27 else 0)
  data_test['day_28'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 28 else 0)
  data_test['day_29'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 29 else 0)
  data_test['day_30'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 30 else 0)
  data_test['day_31'] = data_test['utc_time'].apply(lambda x: 1 if x.day == 31 else 0)
  data_test['month_8'] = data_test['utc_time'].apply(lambda x: 1 if x.month == 8 else 0)
  data_test['month_9'] = data_test['utc_time'].apply(lambda x: 1 if x.month == 9 else 0)
  data_test['month_10'] = data_test['utc_time'].apply(lambda x: 1 if x.month == 10 else 0)
  data_test['month_11'] = data_test['utc_time'].apply(lambda x: 1 if x.month == 11 else 0)

In [ ]:
fill_columns(data_test)
fill_columns(data_train)

In [ ]:
data_train = data_train.drop(columns = 'utc_time')

In [ ]:
data_test = data_test.drop(columns = 'utc_time')

In [ ]:
data_train

,Name,id,lon,lat,value,irb_value,wvb_b09,b09_b10,b10_b16,b11_irb,...,day_26,day_27,day_28,day_29,day_30,day_31,month_8,month_9,month_10,month_11
1,262160,ThanhSon3,108.8432,12.03908,0.2,270.19995,-9.05474,-5.14453,-2.87855,-2.55908,...,0,0,0,0,0,0,0,0,1,0
6,109926,MoCay,106.3353,10.13295,2.4,286.41003,-250.66998,-7.53669,-10.15246,-2.39807,...,0,0,0,1,0,0,0,0,1,0
7,90151,TaPhinh,103.3641,21.99180,0.8,254.68500,-5.92994,-2.04144,-1.11261,-2.56500,...,0,0,0,0,0,0,1,0,0,0
12,909143,Cầu Hà Tân,107.9346,15.84703,1.0,281.01154,-6.80475,-6.45093,-11.35059,-2.33614,...,0,0,0,0,0,0,0,1,0,0
14,91825,MaNoi,108.6939,11.65750,0.2,238.24500,-2.94098,-0.94501,-6.28375,-9.30000,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514113,61840,CaoRam,105.5041,20.83234,1.4,263.68000,-7.42224,-6.59124,-4.91474,-0.57453,...,0,0,0,1,0,0,0,0,1,0
514115,74428,DakLay,107.7291,15.08062,2.6,271.24000,-7.55096,-6.80194,-7.72375,-3.05000,...,0,0,0,0,0,0,0,1,0,0
514117,625783,Ea Lâm,108.7714,13.07167,2.8,269.14667,-10.70477,-5.98956,-3.46766,-2.60761,...,0,0,0,0,0,0,0,0,1,0
514118,521170,LacDuong,108.4211,12.01222,2.4,271.24000,-10.78906,-7.18421,-6.06824,-2.51667,...,0,0,0,0,0,0,0,1,0,0
514121,806374,DongGiao,105.9176,20.15627,0.2,267.00000,-7.98328,-7.75628,-5.36285,-1.02454,...,0,0,0,1,0,0,0,0,1,0

In [ ]:
data_train = data_train.sort_values(by = ['id', 'date', 'hour'])

In [ ]:
data_test = data_test.sort_values(by = ['id', 'date', 'hour'])

In [ ]:
data_train

,Name,id,lon,lat,value,irb_value,wvb_b09,b09_b10,b10_b16,b11_irb,...,day_26,day_27,day_28,day_29,day_30,day_31,month_8,month_9,month_10,month_11
269522,356642,A Bung,107.0261,16.36830,1.0,265.90723,-7.87616,-8.39807,-7.45459,-1.06446,...,0,0,0,0,0,0,0,0,0,0
136622,356642,A Bung,107.0261,16.36830,15.6,225.62500,-2.35748,0.47748,-0.45429,-0.29102,...,0,0,0,0,0,0,0,0,0,0
348212,356642,A Bung,107.0261,16.36830,1.0,260.20996,-9.43219,-5.39379,-2.23621,-2.01392,...,0,0,0,0,0,0,1,0,0,0
393814,356642,A Bung,107.0261,16.36830,0.2,259.61365,-8.69440,-4.58129,-2.42072,-2.06165,...,0,0,0,0,0,0,1,0,0,0
513099,356642,A Bung,107.0261,16.36830,0.6,264.24000,-8.93762,-5.24445,-3.90924,-2.31996,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345006,299387,Đức Vân - Bắc Kạn,106.0331,22.44722,0.2,291.11400,-8.43219,-8.75628,-16.15290,-3.34800,...,0,0,0,0,0,0,0,1,0,0
426517,299387,Đức Vân - Bắc Kạn,106.0331,22.44722,0.2,259.61365,-5.37335,-3.78521,-5.07142,-1.41761,...,0,0,0,0,0,0,0,1,0,0
282671,299387,Đức Vân - Bắc Kạn,106.0331,22.44722,0.2,252.74902,-6.38220,-3.31433,-0.24457,-1.34900,...,0,0,0,0,0,0,0,1,0,0
202749,299387,Đức Vân - Bắc Kạn,106.0331,22.44722,0.2,254.68500,-6.28107,-2.16149,-1.33851,-2.56500,...,0,0,0,0,0,0,0,1,0,0
438120,299387,Đức Vân - Bắc Kạn,106.0331,22.44722,0.6,257.80505,-7.28107,-2.90429,-2.18970,-2.22503,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
data_test

,Name,id,lon,lat,value,irb_value,wvb_b09,b09_b10,b10_b16,b11_irb,...,day_26,day_27,day_28,day_29,day_30,day_31,month_8,month_9,month_10,month_11
5376,356642,A Bung,107.0261,16.36830,1.0,246.61108,-4.94666,-2.65191,1.74188,0.25391,...,0,0,0,0,0,0,0,0,1,0
14384,356642,A Bung,107.0261,16.36830,0.6,256.57202,-5.58172,-0.94049,-0.70374,-2.35205,...,0,0,0,0,0,0,0,0,1,0
12726,356642,A Bung,107.0261,16.36830,2.2,270.71997,-5.88922,-3.07624,-5.79187,-2.52997,...,0,0,0,0,0,0,0,0,1,0
6560,356642,A Bung,107.0261,16.36830,1.8,264.80000,-5.29730,-1.69372,-2.86024,-2.28730,...,0,0,0,0,0,0,0,0,1,0
9832,356642,A Bung,107.0261,16.36830,8.2,269.68000,-6.73425,-4.43123,-3.00182,-2.58820,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18412,472622,Đức Phú,108.8367,14.94528,7.6,280.07922,-9.58977,-5.87550,-6.16113,-2.33307,...,0,0,0,0,0,0,0,0,1,0
14692,472622,Đức Phú,108.8367,14.94528,2.0,274.77540,-8.46667,-5.65870,-2.11340,-1.38690,...,0,0,0,0,0,0,0,0,1,0
7591,472622,Đức Phú,108.8367,14.94528,19.8,272.78003,-9.80749,-4.48152,-2.31964,-2.46668,...,0,0,0,0,0,0,0,0,1,0
14877,472622,Đức Phú,108.8367,14.94528,23.6,272.78003,-11.25158,-5.23152,-2.31964,-1.94336,...,0,0,0,0,0,0,0,0,1,0
4192,472622,Đức Phú,108.8367,14.94528,3.4,273.78003,-9.48498,-5.65870,-2.11340,-1.40003,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
data_train = data_train.drop(index=data_train.loc[data_train['value'] < 1.8].index).reset_index(drop=True)

In [ ]:
data_test = data_test.drop(index=data_test.loc[data_test['value'] < 1.8].index).reset_index(drop=True)

In [ ]:
data_train = data_train.reset_index(drop = True)

In [ ]:
data_test = data_test.reset_index(drop = True)

In [ ]:

input_train = []
output_train = []
no_of_sample = len(data_train)
WINDOW_SIZE = 3 # 3 gio
for i in range(no_of_sample - WINDOW_SIZE + 1):
  next_idx = i + WINDOW_SIZE - 1
  if(data_train['hour'][next_idx] == (data_train['hour'][i] + WINDOW_SIZE - 1) % 24 and data_train['hour'][next_idx - 1] == (data_train['hour'][i] + WINDOW_SIZE - 2) and data_train['lat'][next_idx] == data_train['lat'][i] ):
    X = data_train.loc[i:i + WINDOW_SIZE - 1]
    X = X.drop(columns = ['hour', 'lat','lon', 'date', 'Name', 'id','value'])
    X.to_numpy()
    input_train.append(X)
    output_train.append(data_train['value'][i+WINDOW_SIZE - 1])

In [ ]:
input_test = []
output_test = []
no_of_sample = len(data_test) 
WINDOW_SIZE = 3 # 3 gio
for i in range(no_of_sample - WINDOW_SIZE + 1):
  next_idx = i + WINDOW_SIZE - 1
  if(data_test['hour'][next_idx] == (data_test['hour'][i] + WINDOW_SIZE - 1) % 24 and data_test['hour'][next_idx - 1] == (data_test['hour'][i] + WINDOW_SIZE - 2) and data_test['lat'][next_idx] == data_test['lat'][i] ):
    X = data_test.loc[i:i + WINDOW_SIZE - 1]
    X = X.drop(columns = ['hour', 'lat','lon', 'date', 'Name', 'id', 'value'])
    X.to_numpy()
    input_test.append(X)
    output_test.append(data_test['value'][i+WINDOW_SIZE - 1])

In [ ]:
X_train = np.array(input_train)

In [ ]:
y_train = np.array(output_train)

In [ ]:
X_test = np.array(input_test)

In [ ]:
y_test = np.array(output_test)

In [ ]:
X_train.shape

(22535, 3, 43)

In [ ]:
X_test.shape

(0,)

In [ ]:

#model
regressor = Sequential()
regressor.add(LSTM(units = 50, input_shape = (X_train.shape[1], X_train.shape[2])))
regressor.add(Dense(units = 1, activation = 'relu'))
regressor.compile(optimizer='adam', loss=MeanSquaredLogarithmicError(), metrics=[r])

In [ ]:
history = regressor.fit(X_train, 
					y_train, 
					epochs=128, 
					batch_size=256, 
					validation_split=0.1)

Epoch 1/128
80/80 [==============================] - 3s 14ms/step - loss: 1.8274 - r: -0.0184 - val_loss: 0.9568 - val_r: -0.1493
Epoch 2/128
80/80 [==============================] - 1s 8ms/step - loss: 0.8511 - r: 0.0172 - val_loss: 0.7255 - val_r: -0.1489
Epoch 3/128
80/80 [==============================] - 1s 7ms/step - loss: 0.6818 - r: -0.0116 - val_loss: 0.6265 - val_r: -0.1315
Epoch 4/128
80/80 [==============================] - 1s 8ms/step - loss: 0.6097 - r: 0.0267 - val_loss: 0.5743 - val_r: -0.1133
Epoch 5/128
80/80 [==============================] - 1s 7ms/step - loss: 0.5687 - r: 0.0053 - val_loss: 0.5431 - val_r: -0.0952
Epoch 6/128
80/80 [==============================] - 1s 7ms/step - loss: 0.5438 - r: -0.0522 - val_loss: 0.5235 - val_r: -0.0823
Epoch 7/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5281 - r: -0.0233 - val_loss: 0.5112 - val_r: -0.0619
Epoch 8/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5181 - r: -0.0047 - val_loss: 0.5033 - val_r: -0.0592
Epoch 9/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5116 - r: -0.0091 - val_loss: 0.4983 - val_r: -0.0480
Epoch 10/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5075 - r: -0.0196 - val_loss: 0.4950 - val_r: -0.0412
Epoch 11/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5049 - r: -0.0065 - val_loss: 0.4930 - val_r: -0.0292
Epoch 12/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5032 - r: -0.0088 - val_loss: 0.4917 - val_r: -0.0325
Epoch 13/128
80/80 [==============================] - 1s 7ms/step - loss: 0.5022 - r: 0.0464 - val_loss: 0.4910 - val_r: -0.0362
Epoch 14/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5016 - r: 0.0256 - val_loss: 0.4905 - val_r: -0.0206
Epoch 15/128
80/80 [==============================] - 1s 7ms/step - loss: 0.5012 - r: 0.0299 - val_loss: 0.4903 - val_r: -0.0021
Epoch 16/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5010 - r: 0.0452 - val_loss: 0.4901 - val_r: -0.0037
Epoch 17/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5008 - r: 0.0133 - val_loss: 0.4900 - val_r: -0.0072
Epoch 18/128
80/80 [==============================] - 1s 7ms/step - loss: 0.5008 - r: 0.0503 - val_loss: 0.4897 - val_r: 0.0517
Epoch 19/128
80/80 [==============================] - 1s 8ms/step - loss: 0.5000 - r: 0.0770 - val_loss: 0.4883 - val_r: 0.1144
Epoch 20/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4983 - r: 0.1637 - val_loss: 0.4866 - val_r: 0.1967
Epoch 21/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4974 - r: 0.1998 - val_loss: 0.4859 - val_r: 0.1844
Epoch 22/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4957 - r: 0.2406 - val_loss: 0.4849 - val_r: 0.2121
Epoch 23/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4945 - r: 0.2500 - val_loss: 0.4838 - val_r: 0.1983
Epoch 24/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4933 - r: 0.2572 - val_loss: 0.4825 - val_r: 0.2075
Epoch 25/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4917 - r: 0.2661 - val_loss: 0.4818 - val_r: 0.2171
Epoch 26/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4904 - r: 0.2851 - val_loss: 0.4809 - val_r: 0.2090
Epoch 27/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4895 - r: 0.2867 - val_loss: 0.4808 - val_r: 0.2250
Epoch 28/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4888 - r: 0.2874 - val_loss: 0.4804 - val_r: 0.2078
Epoch 29/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4873 - r: 0.2956 - val_loss: 0.4786 - val_r: 0.2198
Epoch 30/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4863 - r: 0.3029 - val_loss: 0.4783 - val_r: 0.2179
Epoch 31/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4855 - r: 0.3063 - val_loss: 0.4773 - val_r: 0.2249
Epoch 32/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4845 - r: 0.3124 - val_loss: 0.4779 - val_r: 0.2274
Epoch 33/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4855 - r: 0.3049 - val_loss: 0.4785 - val_r: 0.2134
Epoch 34/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4844 - r: 0.3158 - val_loss: 0.4758 - val_r: 0.2270
Epoch 35/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4829 - r: 0.3170 - val_loss: 0.4753 - val_r: 0.2272
Epoch 36/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4816 - r: 0.3318 - val_loss: 0.4748 - val_r: 0.2280
Epoch 37/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4804 - r: 0.3360 - val_loss: 0.4756 - val_r: 0.2242
Epoch 38/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4807 - r: 0.3341 - val_loss: 0.4736 - val_r: 0.2330
Epoch 39/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4792 - r: 0.3465 - val_loss: 0.4743 - val_r: 0.2363
Epoch 40/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4784 - r: 0.3473 - val_loss: 0.4744 - val_r: 0.2422
Epoch 41/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4783 - r: 0.3485 - val_loss: 0.4727 - val_r: 0.2433
Epoch 42/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4770 - r: 0.3504 - val_loss: 0.4723 - val_r: 0.2446
Epoch 43/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4762 - r: 0.3502 - val_loss: 0.4717 - val_r: 0.2443
Epoch 44/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4755 - r: 0.3548 - val_loss: 0.4729 - val_r: 0.2449
Epoch 45/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4756 - r: 0.3549 - val_loss: 0.4737 - val_r: 0.2463
Epoch 46/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4754 - r: 0.3542 - val_loss: 0.4717 - val_r: 0.2485
Epoch 47/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4745 - r: 0.3616 - val_loss: 0.4718 - val_r: 0.2473
Epoch 48/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4741 - r: 0.3627 - val_loss: 0.4701 - val_r: 0.2533
Epoch 49/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4730 - r: 0.3638 - val_loss: 0.4737 - val_r: 0.2419
Epoch 50/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4733 - r: 0.3653 - val_loss: 0.4713 - val_r: 0.2521
Epoch 51/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4723 - r: 0.3680 - val_loss: 0.4704 - val_r: 0.2553
Epoch 52/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4717 - r: 0.3696 - val_loss: 0.4719 - val_r: 0.2472
Epoch 53/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4713 - r: 0.3712 - val_loss: 0.4702 - val_r: 0.2599
Epoch 54/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4714 - r: 0.3714 - val_loss: 0.4702 - val_r: 0.2619
Epoch 55/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4713 - r: 0.3697 - val_loss: 0.4698 - val_r: 0.2581
Epoch 56/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4708 - r: 0.3787 - val_loss: 0.4688 - val_r: 0.2571
Epoch 57/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4703 - r: 0.3801 - val_loss: 0.4701 - val_r: 0.2651
Epoch 58/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4696 - r: 0.3768 - val_loss: 0.4698 - val_r: 0.2558
Epoch 59/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4707 - r: 0.3772 - val_loss: 0.4696 - val_r: 0.2609
Epoch 60/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4689 - r: 0.3813 - val_loss: 0.4691 - val_r: 0.2615
Epoch 61/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4688 - r: 0.3865 - val_loss: 0.4696 - val_r: 0.2598
Epoch 62/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4683 - r: 0.3859 - val_loss: 0.4701 - val_r: 0.2724
Epoch 63/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4674 - r: 0.3868 - val_loss: 0.4691 - val_r: 0.2789
Epoch 64/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4679 - r: 0.3902 - val_loss: 0.4664 - val_r: 0.2742
Epoch 65/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4664 - r: 0.3941 - val_loss: 0.4667 - val_r: 0.2819
Epoch 66/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4656 - r: 0.4023 - val_loss: 0.4675 - val_r: 0.2906
Epoch 67/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4649 - r: 0.4063 - val_loss: 0.4674 - val_r: 0.2902
Epoch 68/128
80/80 [==============================] - 1s 9ms/step - loss: 0.4655 - r: 0.4070 - val_loss: 0.4676 - val_r: 0.2963
Epoch 69/128
80/80 [==============================] - 1s 12ms/step - loss: 0.4672 - r: 0.4016 - val_loss: 0.4674 - val_r: 0.2851
Epoch 70/128
80/80 [==============================] - 1s 13ms/step - loss: 0.4638 - r: 0.4105 - val_loss: 0.4679 - val_r: 0.2855
Epoch 71/128
80/80 [==============================] - 1s 14ms/step - loss: 0.4641 - r: 0.4108 - val_loss: 0.4659 - val_r: 0.2883
Epoch 72/128
80/80 [==============================] - 1s 12ms/step - loss: 0.4636 - r: 0.4145 - val_loss: 0.4681 - val_r: 0.2836
Epoch 73/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4629 - r: 0.4169 - val_loss: 0.4644 - val_r: 0.3005
Epoch 74/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4626 - r: 0.4207 - val_loss: 0.4633 - val_r: 0.3022
Epoch 75/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4641 - r: 0.4175 - val_loss: 0.4646 - val_r: 0.2980
Epoch 76/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4621 - r: 0.4230 - val_loss: 0.4658 - val_r: 0.3057
Epoch 77/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4632 - r: 0.4196 - val_loss: 0.4654 - val_r: 0.2933
Epoch 78/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4618 - r: 0.4253 - val_loss: 0.4640 - val_r: 0.3047
Epoch 79/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4619 - r: 0.4280 - val_loss: 0.4623 - val_r: 0.3059
Epoch 80/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4601 - r: 0.4276 - val_loss: 0.4639 - val_r: 0.3041
Epoch 81/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4598 - r: 0.4311 - val_loss: 0.4626 - val_r: 0.3102
Epoch 82/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4590 - r: 0.4321 - val_loss: 0.4671 - val_r: 0.2924
Epoch 83/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4588 - r: 0.4354 - val_loss: 0.4648 - val_r: 0.3090
Epoch 84/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4586 - r: 0.4394 - val_loss: 0.4707 - val_r: 0.3013
Epoch 85/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4584 - r: 0.4395 - val_loss: 0.4628 - val_r: 0.3113
Epoch 86/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4576 - r: 0.4461 - val_loss: 0.4616 - val_r: 0.3160
Epoch 87/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4579 - r: 0.4448 - val_loss: 0.4611 - val_r: 0.3261
Epoch 88/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4585 - r: 0.4450 - val_loss: 0.4616 - val_r: 0.3254
Epoch 89/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4572 - r: 0.4447 - val_loss: 0.4642 - val_r: 0.3156
Epoch 90/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4563 - r: 0.4491 - val_loss: 0.4632 - val_r: 0.3229
Epoch 91/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4563 - r: 0.4518 - val_loss: 0.4638 - val_r: 0.3188
Epoch 92/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4566 - r: 0.4518 - val_loss: 0.4620 - val_r: 0.3171
Epoch 93/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4558 - r: 0.4548 - val_loss: 0.4654 - val_r: 0.3023
Epoch 94/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4565 - r: 0.4480 - val_loss: 0.4635 - val_r: 0.3064
Epoch 95/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4549 - r: 0.4587 - val_loss: 0.4621 - val_r: 0.3355
Epoch 96/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4546 - r: 0.4558 - val_loss: 0.4620 - val_r: 0.3273
Epoch 97/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4556 - r: 0.4546 - val_loss: 0.4625 - val_r: 0.3280
Epoch 98/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4549 - r: 0.4651 - val_loss: 0.4639 - val_r: 0.3193
Epoch 99/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4548 - r: 0.4646 - val_loss: 0.4612 - val_r: 0.3340
Epoch 100/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4542 - r: 0.4720 - val_loss: 0.4644 - val_r: 0.3247
Epoch 101/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4535 - r: 0.4670 - val_loss: 0.4667 - val_r: 0.3199
Epoch 102/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4533 - r: 0.4685 - val_loss: 0.4616 - val_r: 0.3400
Epoch 103/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4530 - r: 0.4727 - val_loss: 0.4604 - val_r: 0.3392
Epoch 104/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4535 - r: 0.4724 - val_loss: 0.4607 - val_r: 0.3251
Epoch 105/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4517 - r: 0.4762 - val_loss: 0.4582 - val_r: 0.3513
Epoch 106/128
80/80 [==============================] - 1s 7ms/step - loss: 0.4508 - r: 0.4804 - val_loss: 0.4580 - val_r: 0.3580
Epoch 107/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4500 - r: 0.4830 - val_loss: 0.4599 - val_r: 0.3335
Epoch 108/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4509 - r: 0.4839 - val_loss: 0.4651 - val_r: 0.3130
Epoch 109/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4504 - r: 0.4858 - val_loss: 0.4639 - val_r: 0.3382
Epoch 110/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4505 - r: 0.4857 - val_loss: 0.4572 - val_r: 0.3481
Epoch 111/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4541 - r: 0.4709 - val_loss: 0.4687 - val_r: 0.3504
Epoch 112/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4515 - r: 0.4819 - val_loss: 0.4582 - val_r: 0.3653
Epoch 113/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4501 - r: 0.4927 - val_loss: 0.4619 - val_r: 0.3437
Epoch 114/128
80/80 [==============================] - 1s 9ms/step - loss: 0.4486 - r: 0.4983 - val_loss: 0.4549 - val_r: 0.3708
Epoch 115/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4481 - r: 0.5002 - val_loss: 0.4568 - val_r: 0.3612
Epoch 116/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4484 - r: 0.5001 - val_loss: 0.4563 - val_r: 0.3534
Epoch 117/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4480 - r: 0.5006 - val_loss: 0.4600 - val_r: 0.3367
Epoch 118/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4471 - r: 0.5069 - val_loss: 0.4595 - val_r: 0.3518
Epoch 119/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4471 - r: 0.5011 - val_loss: 0.4609 - val_r: 0.3441
Epoch 120/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4463 - r: 0.5092 - val_loss: 0.4541 - val_r: 0.3757
Epoch 121/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4461 - r: 0.5106 - val_loss: 0.4561 - val_r: 0.3694
Epoch 122/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4463 - r: 0.5123 - val_loss: 0.4596 - val_r: 0.3632
Epoch 123/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4452 - r: 0.5161 - val_loss: 0.4613 - val_r: 0.3424
Epoch 124/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4449 - r: 0.5181 - val_loss: 0.4523 - val_r: 0.3805
Epoch 125/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4446 - r: 0.5170 - val_loss: 0.4555 - val_r: 0.3726
Epoch 126/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4438 - r: 0.5150 - val_loss: 0.4522 - val_r: 0.3674
Epoch 127/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4437 - r: 0.5238 - val_loss: 0.4576 - val_r: 0.3467
Epoch 128/128
80/80 [==============================] - 1s 8ms/step - loss: 0.4440 - r: 0.5231 - val_loss: 0.4587 - val_r: 0.3538

In [ ]:
 y_predict = regressor.predict(X_test).flatten()

ValueError: ignored

In [ ]:
y_predict.shape

In [ ]:
y_predict[0:5]

In [ ]:
y_train_predict = regressor.predict(X_train).flatten()

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model train vs validation msle')
plt.ylabel('msle')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='lower right')
plt.show()

In [ ]:
plt.plot(history.history['r'])
plt.plot(history.history['val_r'])
plt.title('model train vs validation r')
plt.ylabel('r')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='lower right')
plt.show()

In [ ]:
print('TRAINING model')
# print(y_train, y_train_pred)
print('Pearson r:', pearsonr(y_train, y_train_predict)[0])
print('RMSE:', np.sqrt(mean_squared_error(y_train, y_train_predict)))
print('MAE:', mean_absolute_error(y_train, y_train_predict))

print('TESTING model')

print('Pearson r:', pearsonr(y_test, y_predict)[0])
print('RMSE:', np.sqrt(mean_squared_error(y_test, y_predict)))
print('MAE:', mean_absolute_error(y_test, y_predict))